name: Check for newer version of nginx container

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  check-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check for newer version of nginx container
        run: |
          current_version=$(grep 'NGINX_VERSION' Dockerfile | awk -F= '{print $2}')
          latest_version=$(curl -sSL "https://nginx.org/en/download.html" | grep -oP 'Stable version.*?(\d+\.\d+\.\d+)' | awk '{print $NF}')
          if [ "$current_version" != "$latest_version" ]; then
            echo "There is a newer version of the nginx container available: $latest_version"
            # BONUS: commit, push, and create a pull request with the newer tag
            #git config --global user.name "GitHub Actions"
            #git config --global user.email "actions@github.com"
            git tag "$latest_version"
            git push origin "$latest_version"
            gh pr create --title "Update nginx to $latest_version" --body "Automated update of nginx container to the latest version." --base main --head "$latest_version"
          else
            echo "The current version of the nginx container is up-to-date."
          fi
