name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  SHORT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Git SHA
      run: ${{ github.sha }}

    - name: Extract first 8 characters of Git SHA
      run: echo "${{ env.SHORT_SHA }}" | cut -c1-8
      id: short_sha 

    - name: Print shortened Git SHA
      run: ${{ steps.short_sha.outputs.stdout }}   
 
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"


    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          repository: github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: fredodughu/top-10-webpage:latest
            