name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  SHORT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Git SHA
      run: echo Git SHA ${{ github.sha }}

    - name: Extract first 8 characters of Git SHA
      run: echo "${{ env.SHORT_SHA }}" | cut -c1-8
      id: short_sha 

    - name: Print shortened Git SHA
      run: echo "${{ steps.short_sha.outputs.stdout }}"
 
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Log in to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: github.com
        username: ${{ github.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:   
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: docker.pkg.github.com/fredodughu/top-10-webpage/nginx:SHA-latest 
            