name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       # Retrieve the secrets
        USERNAME=${{ secrets.USERNAME }}
        PASSWORD=${{ secrets.PASSWORD }}
          
       # Use the secrets in your code
      echo "Username is $USERNAME and password is $PASSWORD" 

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: fredodughu/top-10-webpage:latest
