name: Build Top 10 Container

on:
  push:
    branches:
      - main

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2 

      - name: Get webpage.html
        run: |
          # Retrieve the Top 10 webpage from the repository
          top_10_webpage=$(cat https://github.com/djfred8/Top-10-Webpage/webpage.html)

      - name: Build container
        run: |
          # Build the container image using Nginx as the webserver and include the Top 10 webpage
          docker build -t top-10-webpage:latest -f Dockerfile .
          docker run -p 8080:80 top-10-webpage:latest

      - name: Return response
        run: |
          # Return the response as a string
          echo "Container built successfully!"
