name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: fredodughu/myimage1
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: docker build -t $fredodughu/myimage1 .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
      
      - name: Push Docker Image
        run: docker push $fredodughu/myimage1
