name: Sysbench Load Test

on:
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: [self-hosted, linux-x64-1, linux-x64-2]
    name: Run Sysbench Load Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sysbench

      - name: Run Sysbench Load Test
        run: |
          sysbench cpu --cpu-max-prime=20000 run --time=60
