name: Sysbench Load Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to'
        required: true
        type: choice
        default: 'staging'
        options: ['staging', 'production', 'development']


jobs:
  loadtest:
    runs-on: ubuntu-latest
    name: Run Sysbench Load Test
    strategy:
      matrix:
        arch: ["amd64", "386", "arm64"]
    steps:
      - name: Install sysbench Test on ${{ inputs.environment }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sysbench

      
      - name: Run Sysbench Load Test on ${{ inputs.environment }}
        run: |
          if [[ "${{ matrix.arch }}" == "amd64" ]]; then
            sysbench cpu --cpu-max-prime=20000 run --time=60
          elif [[ "${{ matrix.arch }}" == "386" ]]; then
            sysbench cpu --cpu-max-prime=20000 run --time=60
          elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
            sysbench cpu --cpu-max-prime=20000 run --time=60
          fi
